name: Upload Release Binaries

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install nightly Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.15.2/install)"
          echo "/home/runner/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_PATH

      - name: Install Anchor
        run: |
          npm install -g @coral-xyz/anchor-cli

      - name: Build
        working-directory: ./account-compression
        run: |
          anchor build
          cp target/deploy/spl_noop.so ../spl_noop.so

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.PAT_TOKEN }}
          files: |
            spl_noop.so
